### PR TITLE
Implement API/websocket side of integration logic.

### PR DESCRIPTION
**Pull request by JustinMullin**

### CODE REVIEW

**Comment by igloude** [comment]
@JustinMullin - the only thing I see is in newPackReceived.js. goToView should be targeting the draft view.

**Comment by JustinMullin** [comment]
@igloude Whoops, yeah I even had that committed locally but hadn't pushed it. =P

**Comment by JustinMullin** [comment]
Corrected now.

**Comment by igloude** [comment]
Quick like :zap:

**Pull request merged**
